/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gelato.gui.client;

import com.gelato.code.rmiserver.ServiceInterface;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *Design related codes are taken from here 
 * URL : https://www.youtube.com/watch?v=ddaY9461FJQ
 * @author Nipuna Thathsara
 */
public class SurveyUI extends javax.swing.JFrame {
    //variables for XY coordinations of the window
    int x;
    int y;
    /**
     * Creates new form SurveyUI
     */
    public SurveyUI() {
        initComponents();
    }
    
    String[] answers = new String[7];
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Q1 = new javax.swing.ButtonGroup();
        Q2 = new javax.swing.ButtonGroup();
        Q3 = new javax.swing.ButtonGroup();
        Q4 = new javax.swing.ButtonGroup();
        Q5 = new javax.swing.ButtonGroup();
        Q6 = new javax.swing.ButtonGroup();
        Q7 = new javax.swing.ButtonGroup();
        Main = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Base = new javax.swing.JPanel();
        page1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Q1a1 = new javax.swing.JLabel();
        Q1a2 = new javax.swing.JLabel();
        Q1next = new javax.swing.JLabel();
        Q1b = new javax.swing.JRadioButton();
        Q1a = new javax.swing.JRadioButton();
        page2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Q2a1 = new javax.swing.JLabel();
        Q2a2 = new javax.swing.JLabel();
        Q2next = new javax.swing.JLabel();
        Q2a = new javax.swing.JRadioButton();
        Q2b = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        page3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Q2a3 = new javax.swing.JLabel();
        Q2a4 = new javax.swing.JLabel();
        Q3next = new javax.swing.JLabel();
        Q3a = new javax.swing.JRadioButton();
        Q3b = new javax.swing.JRadioButton();
        page4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Q2a5 = new javax.swing.JLabel();
        Q2a6 = new javax.swing.JLabel();
        Q4next = new javax.swing.JLabel();
        Q2a13 = new javax.swing.JLabel();
        Q2a14 = new javax.swing.JLabel();
        Q2a15 = new javax.swing.JLabel();
        Q4a = new javax.swing.JRadioButton();
        Q4b = new javax.swing.JRadioButton();
        Q4c = new javax.swing.JRadioButton();
        Q4d = new javax.swing.JRadioButton();
        Q4e = new javax.swing.JRadioButton();
        page5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Q2a7 = new javax.swing.JLabel();
        Q2a8 = new javax.swing.JLabel();
        Q5next = new javax.swing.JLabel();
        Q2a17 = new javax.swing.JLabel();
        Q5a = new javax.swing.JRadioButton();
        Q5b = new javax.swing.JRadioButton();
        Q5c = new javax.swing.JRadioButton();
        page6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Q2a9 = new javax.swing.JLabel();
        Q2a10 = new javax.swing.JLabel();
        Q6next = new javax.swing.JLabel();
        Q6a = new javax.swing.JRadioButton();
        Q6b = new javax.swing.JRadioButton();
        page7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Q2a11 = new javax.swing.JLabel();
        Q2a12 = new javax.swing.JLabel();
        Submit = new javax.swing.JLabel();
        Q2a18 = new javax.swing.JLabel();
        Q7a = new javax.swing.JRadioButton();
        Q7b = new javax.swing.JRadioButton();
        Q7c = new javax.swing.JRadioButton();
        endpoint = new javax.swing.JPanel();
        exitbtn = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        menubtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        Main.setForeground(new java.awt.Color(153, 51, 255));

        Header.setBackground(new java.awt.Color(255, 0, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ISLE OF GELATO");
        jLabel2.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        Base.setLayout(new java.awt.CardLayout());

        page1.setBackground(new java.awt.Color(219, 36, 90));
        page1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("1. Are you an ice cream lover?");
        page1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 13, 687, 31));

        Q1a1.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q1a1.setForeground(new java.awt.Color(255, 255, 255));
        Q1a1.setText("No");
        page1.add(Q1a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 132, 160, 31));

        Q1a2.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q1a2.setForeground(new java.awt.Color(255, 255, 255));
        Q1a2.setText("Yes");
        page1.add(Q1a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 83, 159, 31));

        Q1next.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q1next.setForeground(new java.awt.Color(255, 255, 255));
        Q1next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q1next.setText("NEXT");
        Q1next.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Q1next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q1nextMouseClicked(evt);
            }
        });
        page1.add(Q1next, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 222, 159, 31));

        Q1b.setBackground(new java.awt.Color(219, 36, 90));
        Q1.add(Q1b);
        page1.add(Q1b, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 132, -1, 31));

        Q1a.setBackground(new java.awt.Color(219, 36, 90));
        Q1.add(Q1a);
        page1.add(Q1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 83, -1, 31));

        Base.add(page1, "card2");

        page2.setBackground(new java.awt.Color(219, 36, 90));
        page2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("2.Do you recommend our ice cream shop to others?");
        page2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 13, 687, 31));

        Q2a1.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a1.setForeground(new java.awt.Color(255, 255, 255));
        Q2a1.setText("Yes");
        page2.add(Q2a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 87, 159, 31));

        Q2a2.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a2.setForeground(new java.awt.Color(255, 255, 255));
        Q2a2.setText("No");
        page2.add(Q2a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 125, 159, 35));

        Q2next.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2next.setForeground(new java.awt.Color(255, 255, 255));
        Q2next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q2next.setText("NEXT");
        Q2next.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Q2next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q2nextMouseClicked(evt);
            }
        });
        page2.add(Q2next, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 206, 159, 31));

        Q2a.setBackground(new java.awt.Color(219, 36, 90));
        Q2.add(Q2a);
        Q2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2aActionPerformed(evt);
            }
        });
        page2.add(Q2a, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 89, -1, 29));

        Q2b.setBackground(new java.awt.Color(219, 36, 90));
        Q2.add(Q2b);
        Q2b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2bActionPerformed(evt);
            }
        });
        page2.add(Q2b, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 125, -1, -1));
        page2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 319, -1, -1));

        Base.add(page2, "card3");

        page3.setBackground(new java.awt.Color(219, 36, 90));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("3. Do you like our ice cream?");

        Q2a3.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a3.setForeground(new java.awt.Color(255, 255, 255));
        Q2a3.setText("Yes");

        Q2a4.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a4.setForeground(new java.awt.Color(255, 255, 255));
        Q2a4.setText("No");

        Q3next.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q3next.setForeground(new java.awt.Color(255, 255, 255));
        Q3next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q3next.setText("NEXT");
        Q3next.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Q3next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q3nextMouseClicked(evt);
            }
        });

        Q3a.setBackground(new java.awt.Color(219, 36, 90));
        Q3.add(Q3a);

        Q3b.setBackground(new java.awt.Color(219, 36, 90));
        Q3.add(Q3b);
        Q3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q3bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout page3Layout = new javax.swing.GroupLayout(page3);
        page3.setLayout(page3Layout);
        page3Layout.setHorizontalGroup(
            page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page3Layout.createSequentialGroup()
                .addGroup(page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Q3next, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(page3Layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(page3Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(page3Layout.createSequentialGroup()
                                    .addComponent(Q3b)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Q2a4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(page3Layout.createSequentialGroup()
                                    .addComponent(Q3a)
                                    .addGap(0, 0, 0)
                                    .addComponent(Q2a3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        page3Layout.setVerticalGroup(
            page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Q2a3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(Q3a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q3b, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q2a4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Q3next, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
        );

        Base.add(page3, "card3");

        page4.setBackground(new java.awt.Color(219, 36, 90));
        page4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("4. What is your favorite ice cream flavor?");
        page4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 11, 687, 31));

        Q2a5.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a5.setForeground(new java.awt.Color(255, 255, 255));
        Q2a5.setText("Vanilla");
        page4.add(Q2a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 159, 31));

        Q2a6.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a6.setForeground(new java.awt.Color(255, 255, 255));
        Q2a6.setText("Chocolate");
        page4.add(Q2a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 159, 35));

        Q4next.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q4next.setForeground(new java.awt.Color(255, 255, 255));
        Q4next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q4next.setText("NEXT");
        Q4next.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Q4next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q4nextMouseClicked(evt);
            }
        });
        page4.add(Q4next, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 159, 31));

        Q2a13.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a13.setForeground(new java.awt.Color(255, 255, 255));
        Q2a13.setText("Fruity");
        page4.add(Q2a13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 159, 35));

        Q2a14.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a14.setForeground(new java.awt.Color(255, 255, 255));
        Q2a14.setText("strawberry");
        page4.add(Q2a14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 159, 35));

        Q2a15.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a15.setForeground(new java.awt.Color(255, 255, 255));
        Q2a15.setText("Chocolate vanilla mix");
        page4.add(Q2a15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 159, 35));

        Q4a.setBackground(new java.awt.Color(219, 36, 90));
        Q4.add(Q4a);
        Q4a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q4aActionPerformed(evt);
            }
        });
        page4.add(Q4a, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 81, -1, 30));

        Q4b.setBackground(new java.awt.Color(219, 36, 90));
        Q4.add(Q4b);
        page4.add(Q4b, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        Q4c.setBackground(new java.awt.Color(219, 36, 90));
        Q4.add(Q4c);
        page4.add(Q4c, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 30));

        Q4d.setBackground(new java.awt.Color(219, 36, 90));
        Q4.add(Q4d);
        page4.add(Q4d, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 30));

        Q4e.setBackground(new java.awt.Color(219, 36, 90));
        Q4.add(Q4e);
        page4.add(Q4e, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 30));

        Base.add(page4, "card3");

        page5.setBackground(new java.awt.Color(219, 36, 90));
        page5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("5. What is your favorite food item rather than ice cream?");
        page5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 13, 687, 31));

        Q2a7.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a7.setForeground(new java.awt.Color(255, 255, 255));
        Q2a7.setText("Milk Shakes");
        page5.add(Q2a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 87, 159, 31));

        Q2a8.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a8.setForeground(new java.awt.Color(255, 255, 255));
        Q2a8.setText("mousses");
        page5.add(Q2a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 184, 159, 35));

        Q5next.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q5next.setForeground(new java.awt.Color(255, 255, 255));
        Q5next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q5next.setText("NEXT");
        Q5next.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Q5next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q5nextMouseClicked(evt);
            }
        });
        page5.add(Q5next, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 159, 31));

        Q2a17.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a17.setForeground(new java.awt.Color(255, 255, 255));
        Q2a17.setText("cakes");
        page5.add(Q2a17, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 131, 159, 35));

        Q5a.setBackground(new java.awt.Color(219, 36, 90));
        Q5.add(Q5a);
        page5.add(Q5a, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 87, -1, 31));

        Q5b.setBackground(new java.awt.Color(219, 36, 90));
        Q5.add(Q5b);
        page5.add(Q5b, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 131, -1, 31));

        Q5c.setBackground(new java.awt.Color(219, 36, 90));
        Q5.add(Q5c);
        page5.add(Q5c, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 184, -1, 31));

        Base.add(page5, "card3");

        page6.setBackground(new java.awt.Color(219, 36, 90));
        page6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("6. Do you like ice cream toppings?");
        page6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 13, 687, 31));

        Q2a9.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a9.setForeground(new java.awt.Color(255, 255, 255));
        Q2a9.setText("Yes");
        page6.add(Q2a9, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 87, 159, 31));

        Q2a10.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a10.setForeground(new java.awt.Color(255, 255, 255));
        Q2a10.setText("No");
        page6.add(Q2a10, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 125, 159, 35));

        Q6next.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q6next.setForeground(new java.awt.Color(255, 255, 255));
        Q6next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Q6next.setText("NEXT");
        Q6next.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Q6next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q6nextMouseClicked(evt);
            }
        });
        page6.add(Q6next, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 200, 159, 31));

        Q6a.setBackground(new java.awt.Color(219, 36, 90));
        Q6.add(Q6a);
        page6.add(Q6a, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 87, -1, 31));

        Q6b.setBackground(new java.awt.Color(219, 36, 90));
        Q6.add(Q6b);
        page6.add(Q6b, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 129, -1, 31));

        Base.add(page6, "card3");

        page7.setBackground(new java.awt.Color(219, 36, 90));
        page7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("7. Rate our ice cream?");
        page7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 13, 687, 31));

        Q2a11.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a11.setForeground(new java.awt.Color(255, 255, 255));
        Q2a11.setText("Bad");
        page7.add(Q2a11, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 87, 159, 31));

        Q2a12.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a12.setForeground(new java.awt.Color(255, 255, 255));
        Q2a12.setText("Average");
        page7.add(Q2a12, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 131, 159, 35));

        Submit.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Submit.setText("Submit");
        Submit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        page7.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 280, 159, 31));

        Q2a18.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        Q2a18.setForeground(new java.awt.Color(255, 255, 255));
        Q2a18.setText("Good");
        page7.add(Q2a18, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 179, 159, 35));

        Q7a.setBackground(new java.awt.Color(219, 36, 90));
        Q7.add(Q7a);
        page7.add(Q7a, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 87, -1, 32));

        Q7b.setBackground(new java.awt.Color(219, 36, 90));
        Q7.add(Q7b);
        page7.add(Q7b, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 131, -1, 32));

        Q7c.setBackground(new java.awt.Color(219, 36, 90));
        Q7.add(Q7c);
        page7.add(Q7c, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 179, -1, 32));

        Base.add(page7, "card3");

        endpoint.setBackground(new java.awt.Color(219, 36, 90));
        endpoint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitbtn.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitbtn.setText("Exit");
        exitbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbtnMouseClicked(evt);
            }
        });
        endpoint.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 209, 159, 31));

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Thank You for Participating in our Survey");
        endpoint.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 40, 383, 50));

        menubtn.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        menubtn.setForeground(new java.awt.Color(255, 255, 255));
        menubtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menubtn.setText("Menu");
        menubtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        menubtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menubtnMouseClicked(evt);
            }
        });
        endpoint.add(menubtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 247, 159, 31));

        Base.add(endpoint, "card3");

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // Close btn
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        // Position the window according to mouse dragging
        int codX = evt.getXOnScreen();
        int codY = evt.getYOnScreen();

        this.setLocation(codX-x, codY-y);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        // Get the current position of the window .
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void Q1nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q1nextMouseClicked
        // code for first question's answer
        try {
            ServiceInterface rmiserv =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");
            answers[0]=rmiserv.YNAnswer(Q1a, Q1b, Q1);
            if(answers[0]!=null)
            {
                //move to the next page
               page1.setVisible(false);
               page2.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(Main, "Please select an Answer ");
            }
            System.out.println("Answer -- >"+answers[0]);
                  
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println("Exception "+ex);
        }
        
        
        
        
    }//GEN-LAST:event_Q1nextMouseClicked

    private void Q2nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q2nextMouseClicked
        // code for second question's answer

        try {
            ServiceInterface rmiserv =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");
            answers[1]=rmiserv.YNAnswer(Q2a, Q2b, Q2);
            if(answers[1]!=null)
            {
                //move to the next page
               page2.setVisible(false);
               page3.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(Main, "Please select an Answer ");
            }
            System.out.println("Answer -- >"+answers[1]);
                  
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println("Exception "+ex);
        }
        
        
    }//GEN-LAST:event_Q2nextMouseClicked

    private void Q3nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q3nextMouseClicked
        //code for third question's answer
        try {
            ServiceInterface rmiserv =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");
            answers[2]=rmiserv.YNAnswer(Q3a, Q3b, Q3);
             if(answers[2]!=null)
            {
                //move to the next page
             page3.setVisible(false);
             page4.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(Main, "Please select an Answer ");
            }

            System.out.println("Answer -- >"+answers[2]);
                  
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println("Exception "+ex);
        }
        
       
       
    }//GEN-LAST:event_Q3nextMouseClicked

    private void Q5nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q5nextMouseClicked
        // code for fifth question's answer
        
        try {
            ServiceInterface rmiserv =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");
            answers[4]=rmiserv.GetItemandRating(Q5a, Q5b,Q5c,Q5,1);
            if(answers[4]!=null)
            {
                //move to the next page
           page5.setVisible(false);
           page6.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(Main, "Please select an Answer ");
            }
            System.out.println("Answer -- >"+answers[4]);
                  
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println("Exception "+ex);
        }
        
        
    }//GEN-LAST:event_Q5nextMouseClicked

    private void Q6nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q6nextMouseClicked
        // code for sixth question's answer
        try {
            ServiceInterface rmiserv =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");
            answers[5]=rmiserv.YNAnswer(Q6a, Q6b, Q6);
            if(answers[5]!=null)
            {
                //move to the next page
                  page6.setVisible(false);
                  page7.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(Main, "Please select an Answer ");
            }
            System.out.println("Answer -- >"+answers[5]);
                  
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println("Exception "+ex);
        }
        
       
    }//GEN-LAST:event_Q6nextMouseClicked

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        // code for seventh question's answer and submission
        try {
            ServiceInterface rmiserv =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");
            answers[6]=rmiserv.GetItemandRating(Q7a, Q7b,Q7c,Q7,2);
            if(answers[6]!=null)
            {
                //move to the next page
                page7.setVisible(false);
                endpoint.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(Main, "Please select an Answer ");
            }
            System.out.println("Answer -- >"+answers[6]);
            System.out.println("Answer -- >"+Arrays.toString(answers));
            String ans = rmiserv.SubmitResults(answers);
            System.out.println("final "+ ans);
                  
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println("Exception "+ex);
        }
       
       
    }//GEN-LAST:event_SubmitMouseClicked

    private void exitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseClicked
        // exit button
        System.exit(0);
    }//GEN-LAST:event_exitbtnMouseClicked

    private void menubtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menubtnMouseClicked
        // Back to main menu
        MainUI nxt = new MainUI();
        setVisible(false);
        nxt.setVisible(true);
    }//GEN-LAST:event_menubtnMouseClicked

    private void Q3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q3bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q3bActionPerformed

    private void Q4nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q4nextMouseClicked
        // code for fourth question's answer
        try {
            ServiceInterface rmiserv =  (ServiceInterface) Naming.lookup("rmi://localhost:1099/db");
            answers[3]=rmiserv.GetIceCream(Q4a, Q4b,Q4c,Q4d,Q4e,Q4);
             if(answers[3]!=null)
            {
                //move to the next page
                page4.setVisible(false);
                page5.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(Main, "Please select an Answer ");
            }

            System.out.println("Answer -- >"+answers[3]);

        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            System.out.println("Exception "+ex);
        }

       
    }//GEN-LAST:event_Q4nextMouseClicked

    private void Q4aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q4aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q4aActionPerformed

    private void Q2bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q2bActionPerformed

    private void Q2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q2aActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SurveyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SurveyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SurveyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SurveyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SurveyUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Main;
    private javax.swing.ButtonGroup Q1;
    private javax.swing.JRadioButton Q1a;
    private javax.swing.JLabel Q1a1;
    private javax.swing.JLabel Q1a2;
    private javax.swing.JRadioButton Q1b;
    private javax.swing.JLabel Q1next;
    private javax.swing.ButtonGroup Q2;
    private javax.swing.JRadioButton Q2a;
    private javax.swing.JLabel Q2a1;
    private javax.swing.JLabel Q2a10;
    private javax.swing.JLabel Q2a11;
    private javax.swing.JLabel Q2a12;
    private javax.swing.JLabel Q2a13;
    private javax.swing.JLabel Q2a14;
    private javax.swing.JLabel Q2a15;
    private javax.swing.JLabel Q2a17;
    private javax.swing.JLabel Q2a18;
    private javax.swing.JLabel Q2a2;
    private javax.swing.JLabel Q2a3;
    private javax.swing.JLabel Q2a4;
    private javax.swing.JLabel Q2a5;
    private javax.swing.JLabel Q2a6;
    private javax.swing.JLabel Q2a7;
    private javax.swing.JLabel Q2a8;
    private javax.swing.JLabel Q2a9;
    private javax.swing.JRadioButton Q2b;
    private javax.swing.JLabel Q2next;
    private javax.swing.ButtonGroup Q3;
    private javax.swing.JRadioButton Q3a;
    private javax.swing.JRadioButton Q3b;
    private javax.swing.JLabel Q3next;
    private javax.swing.ButtonGroup Q4;
    private javax.swing.JRadioButton Q4a;
    private javax.swing.JRadioButton Q4b;
    private javax.swing.JRadioButton Q4c;
    private javax.swing.JRadioButton Q4d;
    private javax.swing.JRadioButton Q4e;
    private javax.swing.JLabel Q4next;
    private javax.swing.ButtonGroup Q5;
    private javax.swing.JRadioButton Q5a;
    private javax.swing.JRadioButton Q5b;
    private javax.swing.JRadioButton Q5c;
    private javax.swing.JLabel Q5next;
    private javax.swing.ButtonGroup Q6;
    private javax.swing.JRadioButton Q6a;
    private javax.swing.JRadioButton Q6b;
    private javax.swing.JLabel Q6next;
    private javax.swing.ButtonGroup Q7;
    private javax.swing.JRadioButton Q7a;
    private javax.swing.JRadioButton Q7b;
    private javax.swing.JRadioButton Q7c;
    private javax.swing.JLabel Submit;
    private javax.swing.JPanel endpoint;
    private javax.swing.JLabel exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel menubtn;
    private javax.swing.JPanel page1;
    private javax.swing.JPanel page2;
    private javax.swing.JPanel page3;
    private javax.swing.JPanel page4;
    private javax.swing.JPanel page5;
    private javax.swing.JPanel page6;
    private javax.swing.JPanel page7;
    // End of variables declaration//GEN-END:variables
}
